# Generated by Django 3.1.2 on 2020-10-23 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigInfo',
            fields=[
                ('responsible_team_id', models.AutoField(primary_key=True, serialize=False)),
                ('payload', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ControlUnit',
            fields=[
                ('control_unit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('control_unit_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PackageInfo',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SFC_SW',
            fields=[
                ('sfc_sw_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sfc_sw_name', models.CharField(max_length=255)),
                ('sfc_description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareEngineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=255)),
                ('team_contact', models.CharField(default='', max_length=255)),
                ('responsible_team', models.CharField(max_length=255)),
                ('responsible_team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.configinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PackageVersionInfo',
            fields=[
                ('package_version_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_version_name', models.CharField(max_length=255)),
                ('package_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.packageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PackageSW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw_ecm', models.CharField(max_length=255)),
                ('sw_etn', models.CharField(max_length=255)),
                ('sw_assembly', models.CharField(max_length=255)),
                ('package_version_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.packageversioninfo')),
            ],
        ),
        migrations.AddField(
            model_name='configinfo',
            name='control_unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.controlunit'),
        ),
        migrations.AddField(
            model_name='configinfo',
            name='sfc_sw_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.sfc_sw'),
        ),
    ]
