# Generated by Django 3.1.2 on 2020-11-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('controller_id', models.AutoField(primary_key=True, serialize=False)),
                ('controller_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('hardware_id', models.AutoField(primary_key=True, serialize=False)),
                ('hardware_name', models.CharField(max_length=255)),
                ('hardware_change', models.CharField(max_length=10, null=True)),
                ('SCP_changed', models.CharField(max_length=10, null=True)),
                ('Diagnose_address_changed', models.CharField(max_length=10, null=True)),
                ('controller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuos.controller')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleVersions',
            fields=[
                ('multiple_version_id', models.AutoField(primary_key=True, serialize=False)),
                ('multiple_version_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SourceAddr',
            fields=[
                ('tla_id', models.AutoField(primary_key=True, serialize=False)),
                ('TLA_source_addr', models.CharField(max_length=255)),
                ('IsMaster', models.CharField(max_length=255)),
                ('EnggDef', models.CharField(max_length=255)),
                ('controller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuos.controller')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('software_id', models.IntegerField()),
                ('software_part', models.CharField(max_length=255)),
                ('software_filename', models.CharField(max_length=255)),
                ('software_version', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('controller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuos.controller')),
                ('hardware_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuos.hardware')),
                ('multiple_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuos.multipleversions')),
                ('tla_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuos.sourceaddr')),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('payload_id', models.CharField(max_length=30)),
                ('payload_changed', models.CharField(max_length=10, null=True)),
                ('source_addr_change', models.CharField(max_length=10, null=True)),
                ('controller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuos.controller')),
                ('hardware_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuos.hardware')),
                ('multiple_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuos.multipleversions')),
            ],
        ),
        migrations.AddField(
            model_name='hardware',
            name='multiple_version_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuos.multipleversions'),
        ),
    ]
